services:
  webserver:
#    image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
    image: "skodak2/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
    depends_on:
      - db
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
      - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
      - "${BASEDIR}/templates/config.php:/var/www/config-docker.php"
      - "${ASSETDIR}/web/nvm_install.sh:/root/nvm_install.sh"
      - "${ASSETDIR}/web/npm_install.sh:/root/npm_install.sh"
      - "${ASSETDIR}/web/php_wrapper:/root/php_wrapper"
      - "${ASSETDIR}/web/backup.sh:/root/backup.sh"
      - "${ASSETDIR}/web/restore.sh:/root/restore.sh"
    environment:
      MOODLE_DOCKER_RUNNING: 1
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: "${MOODLE_DOCKER_BROWSER_NAME}"
      COMPOSE_PROJECT_NAME:  "${COMPOSE_PROJECT_NAME}"
      COMPOSER_ALLOW_SUPERUSER: 1
  exttests:
    image: moodlehq/moodle-exttests
    volumes:
      - "${ASSETDIR}/exttests/apache2_ports.conf:/etc/apache2/ports.conf"
      - "${ASSETDIR}/exttests/apache2.conf:/etc/apache2/sites-enabled/000-default.conf"
