services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
  db:
    image: postgres:${MOODLE_DOCKER_DB_VERSION:-16}
    command: postgres -c synchronous_commit=off -c full_page_writes=off
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: moodle
      POSTGRES_INITDB_ARGS: "--no-sync"
    volumes:
      - "${ASSETDIR}/db/pgsql_wait.sh:/mdc_db_wait.sh"
      - "${ASSETDIR}/db/pgsql_backup.sh:/mdc_db_backup.sh"
      - "${ASSETDIR}/db/pgsql_restore.sh:/mdc_db_restore.sh"
